backbone = 'vgg16'
backbone_out_channels = 512
backbone_stride = 32
anchor_sizes = [64]
anchor_ratios = [1]
image_size = (224, 224)
pre_nms_top_n = {'training': 48, 'testing': 48}
proposal_min_size = 5
objectness_prob_threshold = 0.3
nms_iou_threshold = 0.
post_nms_top_n = {'training': 10, 'testing': 10}
nms_iou_neg_threshold = 0.001
nms_iou_pos_threshold = 0.1
rpn_batch_size = 2
roi_output_size = (7, 7)
roi_spatial_scale = 0.03125
fast_nms_iou_pos_threshold = 0.3
fast_nms_iou_neg_threshold = 0.1
representation_dim = 128
num_classes = 2
fast_rcnn_batch_size = 2
inference_score_thresh = 0.3
fast_post_nms_top_n = {'training': 5, 'testing': 5}
inference_nms_thresh = 0.3
detections_per_img = 10